/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PortfolioRouteRouteImport } from './routes/portfolio/route'
import { Route as LeaderboardRouteRouteImport } from './routes/leaderboard/route'
import { Route as IndexRouteRouteImport } from './routes/index/route'
import { Route as FundIdRouteRouteImport } from './routes/fund.$id/route'
import { Route as AssetTickerRouteRouteImport } from './routes/asset.$ticker/route'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRouteRoute = PortfolioRouteRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRouteRoute = LeaderboardRouteRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const FundIdRouteRoute = FundIdRouteRouteImport.update({
  id: '/fund/$id',
  path: '/fund/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetTickerRouteRoute = AssetTickerRouteRouteImport.update({
  id: '/asset/$ticker',
  path: '/asset/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/leaderboard': typeof LeaderboardRouteRoute
  '/portfolio': typeof PortfolioRouteRoute
  '/settings': typeof SettingsRoute
  '/asset/$ticker': typeof AssetTickerRouteRoute
  '/fund/$id': typeof FundIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/leaderboard': typeof LeaderboardRouteRoute
  '/portfolio': typeof PortfolioRouteRoute
  '/settings': typeof SettingsRoute
  '/asset/$ticker': typeof AssetTickerRouteRoute
  '/fund/$id': typeof FundIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/leaderboard': typeof LeaderboardRouteRoute
  '/portfolio': typeof PortfolioRouteRoute
  '/settings': typeof SettingsRoute
  '/asset/$ticker': typeof AssetTickerRouteRoute
  '/fund/$id': typeof FundIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/portfolio'
    | '/settings'
    | '/asset/$ticker'
    | '/fund/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/portfolio'
    | '/settings'
    | '/asset/$ticker'
    | '/fund/$id'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/portfolio'
    | '/settings'
    | '/asset/$ticker'
    | '/fund/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  LeaderboardRouteRoute: typeof LeaderboardRouteRoute
  PortfolioRouteRoute: typeof PortfolioRouteRoute
  SettingsRoute: typeof SettingsRoute
  AssetTickerRouteRoute: typeof AssetTickerRouteRoute
  FundIdRouteRoute: typeof FundIdRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund/$id': {
      id: '/fund/$id'
      path: '/fund/$id'
      fullPath: '/fund/$id'
      preLoaderRoute: typeof FundIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$ticker': {
      id: '/asset/$ticker'
      path: '/asset/$ticker'
      fullPath: '/asset/$ticker'
      preLoaderRoute: typeof AssetTickerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  LeaderboardRouteRoute: LeaderboardRouteRoute,
  PortfolioRouteRoute: PortfolioRouteRoute,
  SettingsRoute: SettingsRoute,
  AssetTickerRouteRoute: AssetTickerRouteRoute,
  FundIdRouteRoute: FundIdRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
