CREATE TABLE "vault_nav" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vault_nav_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vault_id" uuid NOT NULL,
	"date" text NOT NULL,
	"value" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "wallets" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "wallets" CASCADE;--> statement-breakpoint
ALTER TABLE "stock_prices" ALTER COLUMN "open" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "stock_prices" ALTER COLUMN "high" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "stock_prices" ALTER COLUMN "low" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "stock_prices" ALTER COLUMN "close" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "vault_nav" ADD CONSTRAINT "vault_nav_vault_id_vaults_id_fk" FOREIGN KEY ("vault_id") REFERENCES "public"."vaults"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "uniq_vault_nav_date" ON "vault_nav" USING btree ("vault_id","date");